### ISSUE TITLE
Mise en place de subscription

### ISSUE THREAD

**Issue by mchaabaoui** [ansforge/annuaire-sante-fhir-serveur#17]
A étudier pour prochaine release
https://build.fhir.org/subscription.html

**Comment by zilliw** [comment]
Bonjour,

Pour information, la ressource Subscription a été mise en place depuis plusieurs mois. Ne rencontrant pas un engouement particulier pour ce service, nous allons prochainement désactiver le "Subscription" pour le moment.

Je clôture le sujet.
