### ISSUE TITLE
Erreur de lien vers le guide de démarrage rapide dans la documentation

### ISSUE THREAD

**Issue by gryckelynck** [ansforge/annuaire-sante-fhir-serveur#19]
# Description du problème

Sur les pages:
- https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/documentation/starters/java-starter.html
- https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/documentation/starters/php-starter.html
- https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/documentation/starters/dotnet-starter.html

Le lien indiqué dans la phrase "Si vous n’avez pas de clé d’API, veuillez suivre la procédure décrite [ici](https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/quick-start/readme)." n'est pas bon.

# Fichier•s concerné•s

Aucun.

# Solution proposée

Remplacer le lien : https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/quick-start/readme
Par : https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/quick-start/quick-start.html

**Comment by mchaabaoui** [comment]
[duplicate](https://github.com/ansforge/annuaire-sante-fhir-documentation/issues/116)
L'erreur a été corrigée.

**Comment by zilliw** [comment]
Bonjour, 

le lien de la documentation a été corrigé.

Nous clôturons l'issue.
