### ISSUE TITLE
Problème d'accès à l'API et aux données

### ISSUE THREAD

**Issue by csissy** [ansforge/annuaire-sante-fhir-serveur#22]
# Description du problème
Comment accède-t-on à l'API maintenant ? Avant j'utilisais l'adresse : https://portail.openfhir.annuaire.sante.fr/fhir/ mais elle ne fonctionne plus. Au temps où cette adresse fonctionnait toujours, le développeur de mon équipe avait relevé le problème suivant :
- Getting 50 resources from this API: https://gateway.api.esante.gouv.fr/fhir/v1/Practitioner
- But not getting basic fields like professional-type, firstName, lastName, address etc
Merci pour votre aide.

# Fichier•s concerné•s

# Solution proposée

**Comment by csissy** [comment]
Bonjour,

J'obtiens le même résultat avec cette adresse (voir capture d'écran).
Pour la deuxième question, oui le développeur ne trouve pas ces informations : professional-type, firstName, lastName, address.


![Capture](https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/108579132/5691ae72-f24b-4492-a9a6-4871049ed888)

**Comment by csissy** [comment]
Ok merci, et pour la deuxième questions ?

**Comment by csissy** [comment]
Je vous remercie pour votre réponse.
Concernant ma deuxième question, concrètement, comment accéder aux données jointes svp ?
![api ressources](https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/108579132/87d472a7-688c-4b8e-beaa-30e294cf915a)

**Comment by mchaabaoui** [comment]
Le mapping MOS/API (en FHIR) est décrit dans le guide d'implémentation (IG) sur cette page  :  https://interop.esante.gouv.fr/ig/fhir/annuaire/artifacts.html
<img width="826" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/6d7c8885-2d26-4748-a34c-0e5a173f8e3a">

1/ Concernant l'entité juridique qui correspond à la ressource Organization, les attributs sont disponibles dans l'API comme suit : 

- raisonSociale & raisonSocialeLongue  : 

 <img width="278" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/f59f0480-3f04-4bbf-9d79-481bcd680c62">

- adresseEJ : 

<img width="468" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/ed10c06c-d6b9-4775-bb41-c1ce70467f47">

- telecommunication : 

<img width="394" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/60aca87c-9bda-4d44-b856-d274e1eafb14">

2/ Concernant le professionnel de santé qui correspond à la ressource Practitioner

- idNatPS : 

<img width="448" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/94bfe17a-4e70-4c3c-a738-a2f308dd3a56">

- idPP (qui correspond ici à un numéro RPPS) : 

<img width="428" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/4d98a9ed-b756-438d-aaa8-fa73b5cbb052">

- diplome/typeDiplome : 

<img width="464" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/aac59547-1be8-48c0-8ee4-71bea8e88c75">

- adresse et tecommunication :  ne sont pas disponibles en accès libre dans l'API, s'agissant de données privées

- nomExercice, prenomExercice et civilite sont positionnés au niveau de la ressource PractitionerRole : 

<img width="314" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/9043135d-0bc4-458e-b235-438eceec83f6">

- profession (se trouve dans PractitionerRole également)  : 

<img width="428" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/443fde30-ba7f-4885-a15b-6adf83b7d606">

- savoirFaire (se trouve dans PractionerRole sous l'objet speciality) : 

<img width="430" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/afcdc57d-01bd-4c29-9e1a-f55c821e38d2">

En espérant avoir répondu à vos questions.
N'hésitez pas à consulter la documentation utilisateur qui contient de nombreux exemples de requêtes : https://ansforge.github.io/annuaire-sante-fhir-documentation/

**Comment by csissy** [comment]
Bonjour,

Je vous remercie beaucoup d'avoir pris le temps de me détailler tous ces éléments. C'est dommage parce que j'aurais pu trouver toutes ces ressources et vous éviter ce travail, mais je suis restée bloquée à mes premières recherches infructueuses. En effet, je ne retrouve toujours pas les ressources Organization suivantes :
![image](https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/108579132/8861113d-f6a8-46d0-9d20-81d0f7ba2ebf)
et
![image](https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/108579132/f64d6cea-2402-4677-a365-b6d9993ba5b8)

Ce sont vos captures d'écran, mais moi dans Organization, je n'ai que les informations du fichier word joint.
[Organization.docx](https://github.com/ansforge/annuaire-sante-fhir-serveur/files/13638667/Organization.docx)

Et juste une dernière précision. J'ai bien compris comment fonctionne la donnée idNatPS avec les éléments suivants :
![image](https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/108579132/e806c64d-c711-43a9-9ced-4068cfb422e0)
J'aimerais juste confirmer avec vous qu'il n'existe pas une donnée directe pour le SIREN nommée numSIREN :
![image](https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/108579132/b97fd08d-3fd7-4499-8c95-40489d729a46)

Cordialement

**Comment by mchaabaoui** [comment]
Pour l'Organization de votre exemple, l'adresse n'est pas renseignée car il s'agit une entité juridique. 
Essayez plutôt cette requête pour trouver les entités géographiques pour lesquelles l'adresse est souvent remplie  :  
https://gateway.api.esante.gouv.fr/fhir/v1/Organization?type=GEOGRAPHICAL-ENTITY

**Comment by mchaabaoui** [comment]
voici un exemple d'une organization avec un numéro siren :  

<img width="240" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/53f316c9-936e-4404-a89e-cd94f918541a">

**Comment by csissy** [comment]
Je vous remercie ! 👍

**Comment by csissy** [comment]
Bonjour,

J'ai à nouveau besoin de votre aide svp. Je souhaite afficher le nom de la profession. Dans l'API ce qui est affiché ce sont des codes correspondants aux noms. Comment afficher les noms des professions svp merci ?
![profession](https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/108579132/3d5fbd49-4181-43ec-b919-8fdd6f30c026)

**Comment by mchaabaoui** [comment]
Bonjour @csissy,

Serait il possible de créer une nouvelle issue ? 
Ensuite, votre ticket sera traité rapidement par nos équipes techniques.
D'avance merci.

**Comment by zilliw** [comment]
Bonjour,

Suite aux réponses apportées par @mchaabaoui, je clôture l'issue.

Cordialement,
