### ISSUE TITLE
Données Profession

### ISSUE THREAD

**Issue by csissy** [ansforge/annuaire-sante-fhir-serveur#23]
Bonjour,

J'ai à nouveau besoin de votre aide svp. Je souhaite afficher le nom de la profession. Dans l'API ce qui est affiché ce sont des codes correspondants aux noms. Comment afficher les noms des professions svp merci ?
profession
![profession](https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/108579132/8ab402ec-77ba-4c54-b637-a0b465850664)

**Comment by mchaabaoui** [comment]
Bonjour @csissy,

1/ merci d 'avoir créé un nouveau ticket  (un ticket=un problème)
2/ Concernant votre question, la référence de la nomenclature utilisée est précisée dans le "system" : https://mos.esante.gouv.fr/NOS/TRE_G15-ProfessionSante/FHIR/TRE-G15-ProfessionSante

Dans le fichier https://mos.esante.gouv.fr/NOS/TRE_G15-ProfessionSante/FHIR/TRE-G15-ProfessionSante/TRE_G15-ProfessionSante-FHIR.json, on trouve ceci : 10/Médecin

<img width="158" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/23aec03b-6e00-4cff-b72c-8c8c9c2edfb9">

**Comment by csissy** [comment]
Merci pour votre réponse, 

Dans ce fichier https://mos.esante.gouv.fr/NOS/TRE_G15-ProfessionSante/FHIR/TRE-G15-ProfessionSante/TRE_G15-ProfessionSante-FHIR.json il n'y a pas toutes les professions, c'est bien cela ?
Ce fichier contient bien toutes les professions ? https://mos.esante.gouv.fr/NOS/TRE_A02-ProfessionSavFaire-CISIS/TRE_A02-ProfessionSavFaire-CISIS.xml

Par hasard, vous n'auriez pas un fichier Excel où je peux trouver la correspondance CodeProfession et NomProfession ?

**Comment by mchaabaoui** [comment]
Je vous invite fortement à jeter un œil à ce portail : https://interop.esante.gouv.fr/ig/fhir/annuaire/0.1.0/StructureDefinition-AS-PractitionerRole.html dans lequel vous trouverez , entre autres, le mapping FHIR/MOS, ainsi que toutes les informations utiles sur le modèle FHIR de l'annuaire santé : StructureDefinition(profils, extensions), Terminologies (CodeSystem, ValueSet, ConceptMap)

Dans la version 1.29 que l'on s'apprête à déployer  en production, le ValueSet à utiliser pour la profession est : 

<img width="832" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/d86743d6-acca-4ac0-a616-fdfbfd218892">

un simple clic sur le lien "Binding" renvoie directement vers la terminologie en question.

A noter que les NOS sont disponibles en plusieurs formats : 

- En accès direct ici : https://mos.esante.gouv.fr/NOS

<img width="498" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/0b1fe257-51a3-4d8d-b42c-6db6a228d608">

- En zip, à cet endroit : https://esante.gouv.fr/interoperabilite/mos-nos/nos 

<img width="397" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/f2f4e99d-b0ca-4b9d-bb7e-8095a63c8725">

**Comment by zilliw** [comment]
Bonjour,

Suite aux réponses apportées par @mchaabaoui, je clôture l'issue.

Cordialement,
