### ISSUE TITLE
Resolution of codes

### ISSUE THREAD

**Issue by der-brecher** [ansforge/annuaire-sante-fhir-serveur#27]
# Description du problème
FHIR resources contain codings which consist of code and (code) system. Retrieved FHIR resources do not contain display texts and the FHIR server rejects calls for resolving the display texts via `<base>/CodeSystem/$lookup?code=<code>&system=<system>` making it impossible to implement GUIs with codings.

# Fichier•s concerné•s
I did not find any way to automatically resolve display texts for code values using their referenced code system.

# Solution proposée
Please provide the `<base>/CodeSystem/$lookup` operation to fetch those display values and/or send the display values with the resources.

**Comment by nriss** [comment]
Hi @der-brecher! Thank you for your comment!
We are currently working on a FHIR Terminology Server (called SMT) to manage that kind of operations (see https://smt.esante.gouv.fr/).

We are progressively loading all your terminology artifacts in this FTS : can you tell us the CS and VS that you are looking for ?

@3abdel3ali FYI

**Comment by der-brecher** [comment]
Oh great, this is what I'm looking for. I want to use all the terminoligies as used by FHIR server's resources Practitioner, PractitionerRole, and Organization, e.g., 

- https://mos.esante.gouv.fr/NOS/TRE_R09-CategorieProfessionnelle/FHIR/TRE-R09-CategorieProfessionnelle
- https://mos.esante.gouv.fr/NOS/TRE_G15-ProfessionSante/FHIR/TRE-G15-ProfessionSante
- https://mos.esante.gouv.fr/NOS/TRE_R38-SpecialiteOrdinale/FHIR/TRE-R38-SpecialiteOrdinale
- https://mos.esante.gouv.fr/NOS/TRE_R04-TypeSavoirFaire/FHIR/TRE-R04-TypeSavoirFaire
- https://mos.esante.gouv.fr/NOS/TRE_G09-DepartementOM/FHIR/TRE-G09-DepartementOM

I tried this but the system cannot be found:
`https://smt.esante.gouv.fr/fhir/CodeSystem/$lookup?system=https://mos.esante.gouv.fr/NOS/TRE_R09-CategorieProfessionnelle/FHIR/TRE-R09-CategorieProfessionnelle&code=C`

**Comment by nriss** [comment]
Yay! The NOS files are not in the SMT for now but it will! I don't know the roadmap about that, maybe @3abdel3ali can tell you

These resources are also packaged [here](https://interop.esante.gouv.fr/ig/nos/) if you want to post them on your own FHIR server

**Comment by der-brecher** [comment]
As a workaround, may I also rely on the files located on the denoted locations like 
`https://mos.esante.gouv.fr/NOS/TRE_R09-CategorieProfessionnelle/FHIR/TRE-R09-CategorieProfessionnelle/TRE_R09-CategorieProfessionnelle-FHIR.json`
for 
`https://mos.esante.gouv.fr/NOS/TRE_R09-CategorieProfessionnelle/FHIR/TRE-R09-CategorieProfessionnelle`?

If so, will they be permanently available? 
Is there any documentation about the file naming (there are some underlines and -FHIR postfix)?

**Comment by nriss** [comment]
The naming rules are available there : https://esante.gouv.fr/sites/default/files/media_entity/documents/nos_conventionnos.pdf (In French, sorry ..)

About the availability : Danièle and @3abdel3ali know better than me, but I think the SMT will be the source of truth in the future

**Comment by der-brecher** [comment]
Thank you, this really helps me a lot!

**Comment by 3abdel3ali** [comment]
your welcome ! @der-brecher  may I ask you on which kind of project are you working ?

**Comment by der-brecher** [comment]
I need to reference ANN information of French physicians in a medical product for compliance reasons.
