### ISSUE TITLE
Accès au données limité ?

### ISSUE THREAD

**Issue by csissy** [ansforge/annuaire-sante-fhir-serveur#29]
Bonjour, je ne parviens à accéder qu'à quelques professionnels à partir de l'API. Par exemple le dentiste Elodie MASTAIL est introuvable. J'aimerais juste confirmer avec vous : s'agit-il d'une limitation d'accès à l'API de votre côté ?  Si ce n'est pas le cas c'est que le problème se situe de mon côté.
Cordialement

**Comment by mchaabaoui** [comment]
Bonjour @csissy,
Actuellement, il n'y a aucune restriction quant à l'utilisation de notre API publique. 
Puis-je avoir la requête ?

**Comment by mchaabaoui** [comment]
De mon côté, j'ai joué ces 2 requêtes :

- une recherche textuelle avec le modifier 'exact' ne retournant aucun résultat : 
.../v1/fhir/PractitionerRole?given:**exact**=Elodie&family:**exact**=MASTAIL

- une recherche avec le modifier 'contains' retournant un résultat : 
.../v1/fhir/PractitionerRole?given:**contains**=Elodie&family:**contains**=MASTAIL 

<img width="476" alt="image" src="https://github.com/ansforge/annuaire-sante-fhir-serveur/assets/70761903/8a646c9c-f4a7-4433-a758-074863892628">

**Comment by csissy** [comment]
Je vous remercie ! Je teste.
