### ISSUE TITLE
Gravitee API subscriptions

### ISSUE THREAD

**Issue by der-brecher** [ansforge/annuaire-sante-fhir-serveur#38]
# Question
Currently, there is no restriction concerning the app for using the API. I'm wondering if any restrictions will be made as soon as the API leaves BETA.

1. Are there any restrictions planned concerning the registered apps? (number of subscriptions, throughput, number of calls, quota, ...)
2. Will the domain of the app be checked?
3. Anything else?

Additionally, I have some general questions concerning the mature system :
1. Do you have any claims on availability? The current system is sometimes unavailable. Will this also apply to the mature API?
2. Are resource IDs guaranteed to be stable over time (e.g., after updates, releases, patches)? If not, how do I perfectly find a specific PractitionerRole then?

**Comment by zilliw** [comment]
Hello,
 
We can provide you with the following information:

- **Regarding Gravitee/restrictions**: Currently, there are no limitations in terms of registered applications. So far no restrictions on throughput, number of subscriptions, number of calls, or quotas. We will determine these parameters after the end of the beta version of the FHIR Annuaire Santé API (scheduled for end 2024). The domain of the application is not technically verified, although it must be specified in the app registration on Gravitee.
- **As previously mentioned**, the FHIR Annuaire Santé API is in beta. We are working to ensure increased availability of the API with our hosting provider.
- **Regarding technical IDs**: The technical ID is not stable over time and can change after releases or patches, just as you mentionned. To ensure the search for a specific ressource, you should rely on identifiers.
We hope this provides answers to your questions.

Best regards,

**Comment by der-brecher** [comment]
Thank you for your response! 
**Regarding the identifification of entities:** I'm wondering how this works for PractitionerRoles as they do not have any identifiers beside the technical ID. My requirement is to recall a PractitionerRole as it defines a certain role of a Practitioner in a certain place. Of course I can identify the Practitioner by identifier but if he works in different locations and different professions - I'm lost and still do not see how to find the specific role then. 
Can you give some advise please?

**Comment by zilliw** [comment]
Hello,

We have already identified this issue with PractitionerRoles. The technical team is currently working on implementing an "identifier" for PractitionerRoles, an attribute that will be permanent.
We hope to provide you with more information for october/november.

Best regards

**Comment by zilliw** [comment]
Following the response provided in the previous comments, I am closing this issue.

**Comment by zilliw** [comment]
Hello @der-brecher ,

We are currently working on the new FHIR implementation guide for the Health Directory. The development phase is now complete, and we are currently in the testing phase. New features will appear in the updated version of the FHIR API, including the introduction of the "Identifier" field in the PractitionerRole resource.

Given the timeline, we believe this API will be released by January 2025 at the latest.

**Comment by der-brecher** [comment]
Hi @zilliw @mchaabaoui,

I'm wondering if the stable identifier for PractitionerRole will come with the 1.1.0 release. I checked the issues connected to the milestone but cannot see any related issue to this issue: https://github.com/ansforge/IG-fhir-annuaire/milestone/5?closed=1

Please let me know if the identifier is part of the release if so where to find any documentation about it.
Thanks!
