### ISSUE TITLE
Resolution of Organization::address::line::streetNameType

### ISSUE THREAD

**Issue by der-brecher** [ansforge/annuaire-sante-fhir-serveur#42]
# Description du problème
The address contains a iso21090-ADXP-streetNameType. How can this code be translated into a display string?

# Fichier•s concerné•s
I tried querying the SMT server but the code system is not supported:
`https://smt.esante.gouv.fr/fhir/CodeSystem/$lookup?system=http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetNameType&code=PL`

# Solution proposée
Could you please give an advise on how to do translate this?

**Comment by nriss** [comment]
Hello! Thank you for the message

In the FHIR point of view, this extension is a string that is not binded to a ValueSet.
This is the reason why you cannot find anything on the SMT

We are going to make further investigation to see how this attribute is populated in our implementation

**Comment by nriss** [comment]
After some research, @mchaabaoui can you confirm that this attribute is linked to this TRE ? 
https://mos.esante.gouv.fr/NOS/TRE_R35-TypeVoie/TRE_R35-TypeVoie.pdf

Thanks!

**Comment by nriss** [comment]
After discussion, you can search for the JDV J103 in the SMT to find all available values 
Canonical url : https://mos.esante.gouv.fr/NOS/JDV_J103-TypeVoie-RASS/FHIR/JDV-J103-TypeVoie-RASS

https://smt.esante.gouv.fr/fhir/ValueSet/JDV-J103-TypeVoie-RASS
