### ISSUE TITLE
Error sur la réponse avec _count >= 3000

### ISSUE THREAD

**Issue by flrt** [ansforge/annuaire-sante-fhir-serveur#46]
# Description du problème
Le paramètre `_count` n'est pas documenté concernant la limite supportée. Il y a peu `_count=10000` fonctionnait. A ce jour, il faut être en dessous de 3000 pour ne pas avoir d'erreur.

avec `_count=3000`, une erreur survient et le retour est ambigu 
- http code = 200 mais pas OperationOutcome
- La réponse est 
```
<preview unavailable: response has exceeded 15000000 bytes limit>
```

# Fichier•s concerné•s

# Solution proposée

- documenter le max de `_count` possible
- si un problème de limite
   - renvoyer 1 OperationOutcome avec un status 4xx ou 5xx

**Comment by zilliw** [comment]
Bonjour,

Merci pour l'intérêt porté à l'API. En testant aujourd'hui le count sur 3000 et 10000, j'obtiens bien une réponse positive avec exactement le bon nombre d'éléments. Nos tests ont été réalisés sur le practitioner et practitionerRole:
- {{api_url}}/PractitionerRole?_count=3000 - statut OK
- {{api_url}}/PractitionerRole?_count=10000 - statut OK
- {{api_url}}/Practitioner?_count=3000 - statut OK
- {{api_url}}/Practitioner?_count=10000 - statut OK

Pouvez-vous m'indiquer si vous rencontrez à nouveau cette erreur ? Si oui, quel est le type d'appel ?

Merci pour votre retour,

Bien Cordialement,

**Comment by zilliw** [comment]
Bonjour,

Je clôture le ticket. N'hésitez pas à ouvrir une nouvelle issue si nécessaire si vous rencontrez d'éventuels anomalies.

Bien Cordialement,
