### ISSUE TITLE
Address.city

### ISSUE THREAD

**Issue by mchaabaoui** [ansforge/annuaire-sante-fhir-serveur#9]
L'adress.city d'organization contient à tort le code postal en plus de la ville.
https://github.com/ansforge/annuaire-sante-fhir-documentation/issues/26

**Comment by mchaabaoui** [comment]
Il s'agit d'un bug sur un module applicatif en amont de l'API FHIR.

**Comment by skt2907** [comment]
Bonjour, est-ce qu'il y a du nouveau concernant ce bug ?

**Comment by zilliw** [comment]
Bonjour,

Je vous informe que cette anomalie a été résolue suite à une mise en production cette semaine.

Je clôture cette Issue.
